# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"%\n\x0eQRLoginRequest\x12\x13\n\x0b\x61\x63\x63ount_ref\x18\x01 \x01(\t\"A\n\x0fQRLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x86\x01\n\x16\x43ompleteProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\")\n\x17\x43ompleteProfileResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"4\n\x11\x45mailLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\x12\x45mailLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\xb0\x01\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0cphone_number\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x18\n\x10password_confirm\x18\x06 \x01(\t\x12\x14\n\x0csponsor_code\x18\x07 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x08 \x01(\t\"O\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0b\n\x03uri\x18\x04 \x01(\t2\x91\x02\n\x0b\x41uthService\x12\x36\n\x07QRLogin\x12\x14.auth.QRLoginRequest\x1a\x15.auth.QRLoginResponse\x12N\n\x0f\x43ompleteProfile\x12\x1c.auth.CompleteProfileRequest\x1a\x1d.auth.CompleteProfileResponse\x12?\n\nEmailLogin\x12\x17.auth.EmailLoginRequest\x1a\x18.auth.EmailLoginResponse\x12\x39\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QRLOGINREQUEST']._serialized_start=20
  _globals['_QRLOGINREQUEST']._serialized_end=57
  _globals['_QRLOGINRESPONSE']._serialized_start=59
  _globals['_QRLOGINRESPONSE']._serialized_end=124
  _globals['_COMPLETEPROFILEREQUEST']._serialized_start=127
  _globals['_COMPLETEPROFILEREQUEST']._serialized_end=261
  _globals['_COMPLETEPROFILERESPONSE']._serialized_start=263
  _globals['_COMPLETEPROFILERESPONSE']._serialized_end=304
  _globals['_EMAILLOGINREQUEST']._serialized_start=306
  _globals['_EMAILLOGINREQUEST']._serialized_end=358
  _globals['_EMAILLOGINRESPONSE']._serialized_start=360
  _globals['_EMAILLOGINRESPONSE']._serialized_end=395
  _globals['_REGISTERREQUEST']._serialized_start=398
  _globals['_REGISTERREQUEST']._serialized_end=574
  _globals['_REGISTERRESPONSE']._serialized_start=576
  _globals['_REGISTERRESPONSE']._serialized_end=655
  _globals['_AUTHSERVICE']._serialized_start=658
  _globals['_AUTHSERVICE']._serialized_end=931
# @@protoc_insertion_point(module_scope)
