FROM brunogasparin/litecoin:latest

# Copy custom entrypoint script
COPY litecoin-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/litecoin-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/litecoin-entrypoint.sh"] 