apiVersion: v1
kind: Service
metadata:
  name: websocket
  namespace: tondeka-app
spec:
  selector:
    app: websocket
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 3000
      protocol: TCP