"""added private key

Revision ID: 60cafc119eef
Revises: e2f84217a6be
Create Date: 2025-08-04 15:10:18.354974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60cafc119eef'
down_revision: Union[str, None] = 'e2f84217a6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'account_type',
               existing_type=postgresql.ENUM('FIAT', 'CRYPTO', name='accounttype'),
               nullable=False)
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('crypto_addresses', sa.Column('private_key', sa.String(length=256), nullable=True))
    op.add_column('crypto_addresses', sa.Column('public_key', sa.String(length=256), nullable=True))
    op.alter_column('crypto_addresses', 'memo',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_addresses', 'memo',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('crypto_addresses', 'public_key')
    op.drop_column('crypto_addresses', 'private_key')
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'account_type',
               existing_type=postgresql.ENUM('FIAT', 'CRYPTO', name='accounttype'),
               nullable=True)
    # ### end Alembic commands ###
