"""Added currency code

Revision ID: 6a38627ad653
Revises: 1d661194d41e
Create Date: 2025-07-16 12:07:38.051220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '6a38627ad653'
down_revision: Union[str, None] = '1d661194d41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _column_exists(table_name, column_name):
    inspector = inspect(op.get_bind())
    columns = [c['name'] for c in inspector.get_columns(table_name)]
    return column_name in columns

def upgrade() -> None:
    print("Adding currency_code to crypto_addresses table...")
    if not _column_exists('crypto_addresses', 'currency_code'):
        op.add_column('crypto_addresses', sa.Column('currency_code', sa.String(length=120), nullable=True))
        # Set a default value for existing rows
        op.execute("UPDATE crypto_addresses SET currency_code = 'BTC' WHERE currency_code IS NULL")
        # Alter column to be non-nullable
        op.alter_column('crypto_addresses', 'currency_code', nullable=False)
    print("currency_code column added.")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_addresses', 'currency_code')
    # ### end Alembic commands ###
