"""Added currency code

Revision ID: 6a38627ad653
Revises: 1d661194d41e
Create Date: 2025-07-16 12:07:38.051220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a38627ad653'
down_revision: Union[str, None] = '1d661194d41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_addresses', sa.Column('currency_code', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_addresses', 'currency_code')
    # ### end Alembic commands ###
