"""Added currency and removed currency_id from accounts

Revision ID: ad43b406e01b
Revises: 6a38627ad653
Create Date: 2025-07-16 15:00:39.625984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad43b406e01b'
down_revision: Union[str, None] = '6a38627ad653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency', sa.String(length=8), nullable=True))
    op.drop_index('ix_accounts_currency_id', table_name='accounts')
    op.drop_constraint('uq_accounts_user_currency', 'accounts', type_='unique')
    op.create_index(op.f('ix_accounts_currency'), 'accounts', ['currency'], unique=False)
    op.drop_constraint('accounts_currency_id_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'currency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('accounts_currency_id_fkey', 'accounts', 'currencies', ['currency_id'], ['id'])
    op.drop_index(op.f('ix_accounts_currency'), table_name='accounts')
    op.create_unique_constraint('uq_accounts_user_currency', 'accounts', ['user_id', 'currency_id'])
    op.create_index('ix_accounts_currency_id', 'accounts', ['currency_id'], unique=False)
    op.drop_column('accounts', 'currency')
    # ### end Alembic commands ###
