apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: tondeka-app
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: set-broker-id
          image: busybox
          command:
            - sh
            - -c
            - |
              echo $(hostname | awk -F'-' '{print $NF}') > /broker-id/broker.id
          volumeMounts:
            - name: broker-id
              mountPath: /broker-id
      containers:
        - name: kafka
          image: bitnami/kafka:3.5.2
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_BROKER_ID_COMMAND
              value: "cat /broker-id/broker.id"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
          command:
            - sh
            - -c
            - |
              export KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://$(hostname).kafka:9092"
              exec /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
            - name: broker-id
              mountPath: /broker-id
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: broker-id
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi