apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: tondeka-app
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: peer
    - port: 3888
      name: election