apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: tondeka-app
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: registry.digitalocean.com/tondeka/auth:latest
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: static-storage
            mountPath: /app/uploads
          envFrom:
            - configMapRef:
                name: auth-configmap
            - configMapRef:
                name: general-configmap
            - secretRef:
                name: auth-secret
            - secretRef:
                name: general-secret
      volumes:
      - name: static-storage
        nfs:
          path: /tondeka/
          readOnly: false
          server: 10.108.0.7