apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  # namespace: app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: okusarobert@gmail.com
    privateKeySecretRef:
      name: letsencrypt-secret-prod
    solvers:
    - http01:
       ingress:
         class: nginx